// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3h36GIEl47nF6mQHmyr5C9-uALnH1Sqs',
    appId: '1:818357899629:web:94f7409284b8d49f56ca64',
    messagingSenderId: '818357899629',
    projectId: 'reddit-clone-flutter-5093c',
    authDomain: 'reddit-clone-flutter-5093c.firebaseapp.com',
    storageBucket: 'reddit-clone-flutter-5093c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7a-UpzM1dik7AZdxY9792prkzqw0ht6w',
    appId: '1:818357899629:android:f0b70f3510875a2b56ca64',
    messagingSenderId: '818357899629',
    projectId: 'reddit-clone-flutter-5093c',
    storageBucket: 'reddit-clone-flutter-5093c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAs21ZTe3KTEa53N_eQeqmqs-6ap-G60TE',
    appId: '1:818357899629:ios:e270d350f1b0521756ca64',
    messagingSenderId: '818357899629',
    projectId: 'reddit-clone-flutter-5093c',
    storageBucket: 'reddit-clone-flutter-5093c.appspot.com',
    iosClientId: '818357899629-f1rb0liukcd6fgktkk4t7ljbdambsg9k.apps.googleusercontent.com',
    iosBundleId: 'com.example.redditCloneFlutter',
  );
}
